
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_category', 'acct', 'Accounting / Auditing', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_category', 'adm', 'Administrative / Clerical', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_category', 'art', 'Art / Design / Entertainment', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_category', 'constr', 'Construction / Property', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_category', 'cust', 'Customer Service', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_category', 'edu', 'Education / Training', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_category', 'eng', 'Engineering', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_category', 'fin', 'Finance / Banking / Insurance', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_category', 'fnb', 'F&amp;B / Tourism / Hospitality', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_category', 'hcpr', 'Health / Beauty / Fitness', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_category', 'hr', 'Human Resources', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_category', 'it', 'Information Technology', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_category', 'lgl', 'Legal / Public / Security', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_category', 'mgmt', 'Management', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_category', 'mnfc', 'Manufacturing / Production', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_category', 'mntnc', 'Maintenance / Repair', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_category', 'othr', 'Others', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_category', 'pr', 'PR / Media / Communications', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_category', 'prch', 'Purchasing / Procurement / Inventory', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_category', 'qa', 'Quality Assurance / Control', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_category', 'sale', 'Sales / Marketing', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_category', 'sci', 'Science / R&amp;D / Research', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_category', 'trans', 'Transportation / Logistics', '1', 'system');                        
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'MY', 'Malaysia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'SG', 'Singapore', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'HK', 'Hong Kong', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'PH', 'Philippines', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'AF', 'Afghanistan', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'AX', 'Åland', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'AL', 'Albania', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'DZ', 'Algeria', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'AS', 'American Samoa', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'AD', 'Andorra', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'AI', 'Anguilla', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'AO', 'Angola', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'AQ', 'Antarctica', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'AG', 'Antigua and Barbuda', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'AR', 'Argentina', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'AM', 'Armenia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'AW', 'Aruba', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'AU', 'Australia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'AT', 'Austria', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'AZ', 'Azerbaijan', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'BS', 'Bahamas', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'BH', 'Bahrain', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'BD', 'Bangladesh', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'BB', 'Barbados', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'BJ', 'Benin', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'BY', 'Belarus', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'BE', 'Belgium', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'BZ', 'Belize', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'BM', 'Bermuda', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'BT', 'Bhutan', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'BO', 'Bolivia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'BQ', 'Bonaire', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'BA', 'Bosnia and Herzegovina', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'BW', 'Botswana', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'BV', 'Bouvet Island', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'BR', 'Brazil', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'IO', 'British Indian Ocean Territory', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'VG', 'British Virgin Islands', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'BN', 'Brunei Darussalam', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'BG', 'Bulgaria', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'BF', 'Burkina Faso', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'BI', 'Burundi', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'KH', 'Cambodia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'CM', 'Cameroon', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'CA', 'Canada', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'CV', 'Cape Verde', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'KY', 'Cayman Islands', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'CF', 'Central African Republic', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'TD', 'Chad', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'CL', 'Chile', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'CN', 'China', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'CX', 'Christmas Island', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'CC', 'Cocos [Keeling] Islands', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'CO', 'Colombia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'KM', 'Comoros', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'CK', 'Cook Islands', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'CR', 'Costa Rica', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'HR', 'Croatia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'CU', 'Cuba', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'CW', 'Curacao', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'CY', 'Cyprus', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'CZ', 'Czechia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'CD', 'Democratic Republic of the Congo', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'DK', 'Denmark', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'DJ', 'Djibouti', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'DM', 'Dominica', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'DO', 'Dominican Republic', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'TL', 'East Timor', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'EC', 'Ecuador', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'EG', 'Egypt', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'SV', 'El Salvador', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'GQ', 'Equatorial Guinea', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'ER', 'Eritrea', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'EE', 'Estonia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'ET', 'Ethiopia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'FK', 'Falkland Islands', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'FO', 'Faroe Islands', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'FJ', 'Fiji', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'FI', 'Finland', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'FR', 'France', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'GF', 'French Guiana', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'PF', 'French Polynesia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'TF', 'French Southern Territories', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'GA', 'Gabon', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'GM', 'Gambia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'GE', 'Georgia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'DE', 'Germany', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'GH', 'Ghana', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'GI', 'Gibraltar', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'GL', 'Greenland', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'GD', 'Grenada', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'GP', 'Guadeloupe', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'GG', 'Guernsey', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'GN', 'Guinea', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'GR', 'Greece', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'GT', 'Guatemala', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'GU', 'Guam', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'GW', 'Guinea-Bissau', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'GY', 'Guyana', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'HT', 'Haiti', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'HM', 'Heard Island and McDonald Islands', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'HN', 'Honduras', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'HU', 'Hungary', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'IS', 'Iceland', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'IN', 'India', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'ID', 'Indonesia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'IR', 'Iran', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'IQ', 'Iraq', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'IE', 'Ireland', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'IM', 'Isle of Man', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'IL', 'Israel', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'IT', 'Italy', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'CI', 'Ivory Coast', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'JM', 'Jamaica', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'JP', 'Japan', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'JE', 'Jersey', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'JO', 'Jordan', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'KZ', 'Kazakhstan', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'KE', 'Kenya', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'KI', 'Kiribati', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'XK', 'Kosovo', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'KG', 'Kyrgyzstan', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'KW', 'Kuwait', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'LA', 'Laos', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'LV', 'Latvia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'LB', 'Lebanon', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'LS', 'Lesotho', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'LR', 'Liberia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'LY', 'Libya', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'LI', 'Liechtenstein', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'LT', 'Lithuania', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'LU', 'Luxembourg', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'MO', 'Macao', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'MK', 'Macedonia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'MG', 'Madagascar', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'MW', 'Malawi', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'MV', 'Maldives', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'ML', 'Mali', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'MT', 'Malta', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'MH', 'Marshall Islands', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'MQ', 'Martinique', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'MR', 'Mauritania', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'MU', 'Mauritius', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'YT', 'Mayotte', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'MX', 'Mexico', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'FM', 'Micronesia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'MC', 'Monaco', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'MN', 'Mongolia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'MD', 'Moldova', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'MA', 'Morocco', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'ME', 'Montenegro', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'MS', 'Montserrat', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'MZ', 'Mozambique', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'MM', 'Myanmar [Burma]', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'NA', 'Namibia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'NR', 'Nauru', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'NP', 'Nepal', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'NL', 'Netherlands', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'NC', 'New Caledonia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'NZ', 'New Zealand', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'NI', 'Nicaragua', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'NE', 'Niger', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'NG', 'Nigeria', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'NU', 'Niue', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'NF', 'Norfolk Island', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'NO', 'Norway', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'MP', 'Northern Mariana Islands', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'KP', 'North Korea', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'OM', 'Oman', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'PK', 'Pakistan', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'PW', 'Palau', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'PS', 'Palestine', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'PA', 'Panama', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'PY', 'Paraguay', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'PE', 'Peru', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'PG', 'Papua New Guinea', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'PN', 'Pitcairn Islands', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'PL', 'Poland', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'PT', 'Portugal', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'PR', 'Puerto Rico', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'QA', 'Qatar', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'RE', 'Réunion', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'CG', 'Republic of the Congo', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'RO', 'Romania', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'RU', 'Russia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'RW', 'Rwanda', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'BL', 'Saint Barthélemy', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'SH', 'Saint Helena', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'KN', 'Saint Kitts and Nevis', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'LC', 'Saint Lucia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'MF', 'Saint Martin', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'PM', 'Saint Pierre and Miquelon', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'VC', 'Saint Vincent and the Grenadines', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'WS', 'Samoa', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'SM', 'San Marino', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'ST', 'São Tomé and Príncipe', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'SA', 'Saudi Arabia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'RS', 'Serbia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'SC', 'Seychelles', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'SL', 'Sierra Leone', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'SX', 'Sint Maarten', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'SI', 'Slovenia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'SK', 'Slovakia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'SN', 'Senegal', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'SB', 'Solomon Islands', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'SO', 'Somalia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'ZA', 'South Africa', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'GS', 'South Georgia and the South Sandwich Islands', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'KR', 'South Korea', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'SS', 'South Sudan', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'ES', 'Spain', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'LK', 'Sri Lanka', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'SD', 'Sudan', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'SR', 'Suriname', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'SJ', 'Svalbard and Jan Mayen', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'SZ', 'Swaziland', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'SE', 'Sweden', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'CH', 'Switzerland', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'SY', 'Syria', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'TZ', 'Tanzania', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_level', '0', 'Others', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_level', '1', 'Internship', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_level', '2', 'Fresh/Entry Level', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_level', '3', 'Junior Executive', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_level', '4', 'Senior Executive', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_level', '5', 'Manager', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_level', '6', 'Senior Manager', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_level', '7', 'Director/C-Level', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'TW', 'Taiwan', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'TJ', 'Tajikistan', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'TH', 'Thailand', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'TK', 'Tokelau', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'TG', 'Togo', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'TO', 'Tonga', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'TT', 'Trinidad and Tobago', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'TN', 'Tunisia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'TR', 'Turkey', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'TM', 'Turkmenistan', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'TC', 'Turks and Caicos Islands', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'TV', 'Tuvalu', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'UM', 'U.S. Minor Outlying Islands', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'VI', 'U.S. Virgin Islands', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'UG', 'Uganda', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'UA', 'Ukraine', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'AE', 'United Arab Emirates', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'UK', 'United Kingdom', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'US', 'United States', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'UY', 'Uruguay', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'UZ', 'Uzbekistan', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'VU', 'Vanuatu', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'VA', 'Vatican City', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'VE', 'Venezuela', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'VN', 'Vietnam', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'WF', 'Wallis and Futuna', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'EH', 'Western Sahara', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'YE', 'Yemen', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'ZM', 'Zambia', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'country', 'ZW', 'Zimbabwe', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_type', 'F', 'Full-time', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_type', 'P', 'Part-time', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_type', 'C', 'Contract', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_type', 'T', 'Temporary', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_type', 'O', 'Other', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'job_type', 'V', 'Not Applicable', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'currency', 'MYR', 'MYR', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'currency', 'SGD', 'SGD', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'currency', 'HKD', 'HKD', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'currency', 'PHP', 'PHP', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'currency', 'AUD', 'AUD', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'currency', 'NZD', 'NZD', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'currency', 'USD', 'USD', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '47', 'Accounting / Tax Services', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '80', 'Advertising / Marketing / PR', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '94', 'Aerospace / Aviation / Airline', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '66', 'Agriculture / Plantation / Fisheries', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '120', 'Alternative Dispute Resolution', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '125', 'Alternative Medicine', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '127', 'Animation', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '19', 'Apparel', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '50', 'Architecture / Interior Designing', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '111', 'Arts / Design / Fashion', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '53', 'Automobile / Vehicle', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '41', 'Banking / Financial Services', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '12', 'BioTechnology / Pharmaceutical', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '49', 'Building Materials', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '161', 'Call Center', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '129', 'Capital Markets', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '54', 'Chemical / Plastic / Petrochemical', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '90', 'Civil Services', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '128', 'Commercial Real Estate', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '118', 'Computer &amp; Network Security', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '3', 'Computer / IT (Hardware)', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '4', 'Computer / IT (Software)', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '2', 'Computer / IT (Misc)', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '109', 'Computer Games', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '5', 'Computer Networking', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '48', 'Construction / Building', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '11', 'Consulting (Business &amp; Management)', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '149', 'Consulting (Science &amp; Technical)', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '24', 'Consumer Electronics', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '25', 'Consumer Products / FMCG', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '91', 'Consumer Services', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '18', 'Cosmetics', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '65', 'Dairy', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '1', 'Defense &amp; Space', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '99', 'Design', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '132', 'E-Learning', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '67', 'Education', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '69', 'Education Management', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '112', 'Electrical &amp; Electronics', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '57', 'Energy / Water / Waste Management', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '51', 'Engineering - Civil / Quantity Survey', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '135', 'Engineering - Electrical / Electronic / Mechanical', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '28', 'Entertainment / Media', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '86', 'Environmental Science / Health / Safety', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '76', 'Executive Office', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '110', 'Exhibitions / Event Management', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '122', 'Facilities Services', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '63', 'Farming', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '43', 'Financial Services', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '38', 'Fine Art', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '34', 'Food &amp; Beverage', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '23', 'Food Production', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '87', 'Freight Forwarding / Shipping', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '101', 'Fund-Raising', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '26', 'Furniture', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '29', 'Gambling &amp; Casinos', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '143', 'Gems / Jewellery', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '138', 'General &amp; Wholesale Trading', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '145', 'Glass, Ceramics &amp; Concrete', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '148', 'Government / Defence', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '75', 'Government Administration', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '124', 'Grooming / Beauty / Fitness', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '14', 'Healthcare / Medical', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '147', 'Heavy Industrial / Machinery', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '68', 'Higher Education', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '31', 'Hotel / Hospitality', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '137', 'Human Resources Management', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '134', 'Import and Export', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '88', 'Individual &amp; Family Services', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '84', 'Information Services', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '96', 'Information Technology', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '42', 'Insurance / Pension Funding', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '140', 'Interior / Graphic Design', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '74', 'International Affairs', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '6', 'Internet', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '45', 'Investment Banking', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '46', 'Investment Management', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '162', 'Journalism', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '73', 'Judiciary', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '10', 'Law / Legal', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '77', 'Law Enforcement', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '9', 'Law Practice', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '72', 'Legislative Office', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '85', 'Libraries', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '150', 'Life Sciences', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '116', 'Logistics and Supply Chain', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '55', 'Machinery', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '151', 'Management Consultancy / Service', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '152', 'Manufacturing / Production', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '95', 'Marine / Aquaculture', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '97', 'Market Research', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '36', 'Media / Publishing', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '126', 'Media Production', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '13', 'Medical / Pharmaceutical', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '17', 'Medical Devices', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '139', 'Mental Health Care', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '71', 'Military', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '56', 'Mining &amp; Metals', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '153', 'Mixed Industry Group', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '35', 'Motion Pictures and Film', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '154', 'Motor Vehicles', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '37', 'Museums and Institutions', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '115', 'Music', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '114', 'Nanotechnology', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '81', 'Newspapers', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '100', 'Non-Profit / Social Services / NGO', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '163', 'Oil / Gas / Petroleum', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '113', 'Online Media', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '160', 'Others', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '123', 'Outsourcing/Offshoring', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '146', 'Packaging and Containers', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '39', 'Performance / Musical / Artistic', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '155', 'Petroleum', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '15', 'Pharmaceuticals', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '131', 'Philanthropy', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '136', 'Photography', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '117', 'Plastics', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '107', 'Political Organization', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '164', 'Polymer / Plastic / Rubber', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '83', 'Printing', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '105', 'Professional Training', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '102', 'Program Development', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '157', 'Property / Real Estate', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '156', 'Property Development', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '98', 'Public Relations', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '78', 'Public Safety', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '79', 'Public Sector / Stat Board', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '82', 'Publishing', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '62', 'Railroad Manufacture', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '64', 'Ranching', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '44', 'Real Estate', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '40', 'Recreational Services', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '89', 'Religious Institutions', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '144', 'Renewables &amp; Environment', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '165', 'Repair &amp; Maintenance Services', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '32', 'Restaurants', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '27', 'Retail / Merchandise', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '70', 'R&amp;D / Survey', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '166', 'Science &amp; Technology', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '121', 'Security / Fire / Controls', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '158', 'Security / Law Enforcement', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '7', 'Semiconductor', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '58', 'Shipbuilding', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '52', 'Space / Aerospace', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '20', 'Sporting Goods', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '33', 'Sports', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '104', 'Staffing and Recruiting', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '167', 'Stockbroking / Securities', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '22', 'Supermarkets', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '8', 'Telecommunication', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '60', 'Textiles / Garment', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '130', 'Think Tanks', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '21', 'Tobacco', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '141', 'Trading and Distribution', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '108', 'Translation', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '92', 'Transportation / Logistics', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '30', 'Tour Agency', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '159', 'Tourism', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '59', 'Utilities / Power', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '106', 'Venture Capital &amp; Private Equity', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '16', 'Veterinary', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '93', 'Warehousing', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '133', 'Wholesale', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '142', 'Wine and Spirits', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '119', 'Wireless', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '61', 'Wood / Fibre / Paper', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_industry', '103', 'Writing and Editing', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_type', 'RA', 'Recruitment Agency', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'employer_type', 'DE', 'Direct Employer', '1', 'system');

INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'core_skill', 'PHP', 'PHP', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'core_skill', 'JAVA', 'JAVA', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'core_skill', 'HTML5', 'HTML5', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'core_skill', 'CSS3', 'CSS3', '1', 'system');

INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'study_field', 'MAT', 'Mathematics', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'study_field', 'PHY', 'Physics', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'study_field', 'CHE', 'Chemistry', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'study_field', 'BIO', 'Biology', '1', 'system');

INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'degree', 'PHD', 'Phd', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'degree', 'MAS', 'Masters', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'degree', 'BAC', 'Bachelors', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'degree', 'DIP', 'Diploma', '1', 'system');

INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'race', 'MAL', 'Malay', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'race', 'IND', 'Indian', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'race', 'CHI', 'Chinese', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'race', 'OTH', 'Others', '1', 'system');

INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'industry', 'CON', 'Construction', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'industry', 'BAK', 'Banking', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'industry', 'OAG', 'Oil and Gas', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'industry', 'ITV', 'IT Vendor', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'industry', 'INS', 'Insurance', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'industry', 'HOS', 'Hospalitity', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'industry', 'HEC', 'Health Care', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'industry', 'AGR', 'Agriculture', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'industry', 'FAB', 'Food and Beverages', '1', 'system');


INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'language', 'ENG', 'English', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'language', 'TAM', 'Tamil', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'language', 'CHI', 'Chinese', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'language', 'MAL', 'Bahasa Malay', '1', 'system');

INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'lang_skill_level', 'EXP', 'Expert', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'lang_skill_level', 'GOOD', 'Good', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'lang_skill_level', 'INT', 'Intermediate', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'lang_skill_level', 'LIM', 'Limited', '1', 'system');
INSERT INTO `joblight`.`lookups` (`lookup_type`, `lookup_code`, `lookup_name`, `active_ind`, `created_by`) VALUES ( 'lang_skill_level', 'BAS', 'Basic', '1', 'system');